<?/* This file was generated by ccHost Content Manager 
[meta]
     type = dynamic_content_page
     desc = _('News')
      t = ccskins/shared/pages/content_page.tpl
      content_page_columns = 3
      limit = 
      content_page_width = 
      content_page_textformat = format
      content_page_paging = 0
      content_page_box = 1
      sort = date
      ord = desc
      content_feed = 1
      topic_type = news

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_paging'] = '0';
$A['content_page_width'] = '';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '3';
$id = empty($_GET['ids']) ? '' : $_GET['ids'];
$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>News</h1>";
cc_query_fmt('f=page&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=desc&type=news&limit=' . $id . '&topic=' . $topic );
$A['macro_names'][] = 'prev_next_links';
 cc_content_feed('datasource=topics&type=news&page=news','News','topics');
?>