<?/*
   This file was generated by ccHost Content Manager

[meta]
     type = dynamic_content_page
     desc = _('Congratulations on a Successful Install')
     page_title = _('Congratulations on a Successful Install')
      content_feed = 0
      content_page_box = 1
      content_page_columns = 2
      content_page_textformat = format
      content_page_width = auto
      content_toc = 0
      limit = 
      ord = asc
      paging = off
      sort = date
      t = ccskins/shared/pages/content_page.tpl
      topic_type = home

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = 'auto';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '2';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=home&limit=&paging=off&topic=' . $topic );
// no paging 
//  
?>

