<?/* This file was generated by ccHost Content Manager 
[meta]
     type = dynamic_content_page
     desc = _('Credits')
           t = ccskins/shared/pages/content_page.tpl
      content_page_columns = 1
      limit = 
      content_page_width = 600px
      content_page_textformat = format
      content_toc = 0
      paging = off
      content_page_box = 0
      sort = date
      ord = desc
      content_feed = 0
      topic_type = credits

[/meta]
*/
$A['content_page_box'] = '0';
$A['content_page_width'] = '600px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '1';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Credits</h1>";
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=desc&type=credits&limit=&paging=off&topic=' . $topic );

//  cc_content_feed('datasource=topics&type=credits&page=credits','Credits','topics');
?>