<?/*
   This file was generated by ccHost Content Manager

[meta]
     type = dynamic_content_page
     desc = _('Earth Day 2009 with Snowflake')
      content_feed = 0
      content_page_box = 1
      content_page_columns = 2
      content_page_textformat = format
      content_page_width = 830px
      content_toc = 0
      limit = 
      ord = asc
      paging = off
      sort = date
      t = ccskins/shared/pages/content_page.tpl
      topic_type = earthday2009

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = '830px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '2';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Earth Day 2009 with Snowflake</h1>";
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=earthday2009&limit=&paging=off&topic=' . $topic );
// no paging 
//  
?>

