<?/* This file was generated by ccHost Content Manager 
[meta]
     type = dynamic_content_page
     desc = _('Find Music')
           t = ccskins/shared/pages/content_page.tpl
      content_page_columns = 2
      limit = 
      content_page_width = 700px
      content_page_textformat = format
      content_toc = 0
      paging = off
      content_page_box = 1
      sort = date
      ord = asc
      content_feed = 0
      topic_type = findmusic

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = '700px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '2';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Find Music</h1>";
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=findmusic&limit=&paging=off&topic=' . $topic );

//  cc_content_feed('datasource=topics&type=findmusic&page=find-music','Find Music','topics');
?>