<?/*
   This file was generated by ccHost Content Manager

[meta]
     type = dynamic_content_page
     desc = _('Imaginashun')
      content_feed = 0
      content_page_box = 1
      content_page_columns = 1
      content_page_textformat = text
      content_page_width = 800px
      content_toc = 0
      limit = 
      ord = asc
      paging = on
      sort = date
      t = ccskins/shared/pages/content_page.tpl
      topic_type = DJ Vadim

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = '800px';
$A['content_page_textformat'] = 'text';
$A['content_page_columns'] = '1';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Imaginashun</h1>";
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=DJ Vadim&limit=&paging=on&topic=' . $topic );
cc_add_content_paging_links($A,'DJ Vadim',$topic,'asc','imaginashun', '');
$A['macro_names'][] = 'prev_next_links';
//  
?>

