<?/*
   This file was generated by ccHost Content Manager

[meta]
     type = dynamic_content_page
     desc = _('ccMixter Podcast')
     page_title = _('ccMixter Podcast')
      content_feed = 1
      content_page_box = 1
      content_page_columns = 1
      content_page_textformat = format
      content_page_width = 610px
      content_toc = ccskins/shared/formats/topic_toc_select.tpl
      limit = 6
      ord = desc
      paging = off
      show_bread_crumbs = 1
      sort = date
      t = ccskins/shared/pages/content_page.tpl
      topic_type = podcast
      breadcrumbs = home,page_title,topic

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = '610px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '1';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
cc_query_fmt('f=html&limit=query&&noexit=1&nomime=1&t=ccskins/shared/formats/topic_toc_select.tpl&page=podcast&sort=date&ord=desc');
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=desc&type=podcast&limit=6&paging=off&topic=' . $topic );
// no paging 
cc_content_feed('datasource=topics&type=podcast&page=podcast','ccMixter Podcast','topics'); 
?>

