<?/*
   This file was generated by ccHost Content Manager

[meta]
     type = dynamic_content_page
     desc = _('RIP - A Remix Manifesto')
      content_feed = 0
      content_page_box = 1
      content_page_columns = 2
      content_page_textformat = format
      content_page_width = 
      content_toc = 0
      limit = 
      ord = desc
      paging = on
      sort = date
      t = ccskins/shared/pages/content_page.tpl
      topic_type = rip

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_width'] = '';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '2';

$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>RIP - A Remix Manifesto</h1>";
cc_query_fmt('f=embed&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=desc&type=rip&limit=&paging=on&topic=' . $topic );
cc_add_content_paging_links($A,'rip',$topic,'desc','rip', '');
$A['macro_names'][] = 'prev_next_links';
//  
?>

