  <style type="text/css">
    span.s1 {text-decoration: underline ; color: #0022f8}
    span.s2 {font: 10.0px Symbol}
    span.s3 {text-decoration: underline}
    span.Apple-tab-span {white-space:pre}
  </style>

<div style="margin: 12px 6%;">
<h1>CCMIXTER TERMS OF USE</h1>

<p class="p3">Please read these terms carefully because they apply to your use of the ccMixter site available at <a href="http://ccMixter.org/"><span class="s1">http://ccMixter.org</span></a> ("ccMixter"). Your use of ccMixter in any way indicates that you have read, understood and agree to these terms. By using ccMixter you also represent that you have the legal authority to accept these terms on behalf of yourself and any party you represent. <b>If you do not agree to these terms, please do not use the site</b>.</p>
<p class="p4"></p>
<p class="p3">ArtisTech Media, LLC ("ArtisTech Media"), a California limited liability
corporation with a business office at 10606 Camino Ruiz, Suite 8-244, San Diego, CA 92126, United States makes
ccMixter available to you to use on these terms.</p>
<p class="p4"></p>
<p class="p3"><b>Changes to these terms:</b> From time to time, ArtisTech Media may change these terms. In that case, we will post the updated terms and post a notice to the discussion board, notifying users of the change. Your continued use of ccMixter after this notification will indicate that you have read, understood and agreed to the current version of these terms.</p>
<p class="p4"></p>
<p class="p3"><b>What you may do with the music on ccMixter:</b> You may use the tracks that you find on ccMixter in accordance with the Creative Commons license that applies to each track. For example, if a track is licensed under a Creative Commons Sampling Plus license (<a href="http://creativecommons.org/licenses/sampling+/1.0/"><span class="s1">http://creativecommons.org/licenses/sampling+/1.0/</span></a>), you may sample, mash-up, or otherwise creatively transform this work for commercial or noncommercial purposes provided that you: (a) attribute the work in the manner specified by the author or licensor; (b) do not use the track to advertise or promote anything other than the work you create from it or yourself; (c) make clear to others the license terms of the track as part of your reuse, and (d) otherwise use the track in accordance with the terms of the Creative Commons Sampling Plus license.</p>
<p class="p4"></p>
<p class="p3">Different Creative Commons licenses may apply to different tracks made available at ccMixter. You must use each track in accordance with its license terms. For this reason, you should check the Creative Commons license that applies to each track before you use it so that you know what you can and cannot do with it. By using ccMixter, you agree that you are solely responsible for your use of any and all tracks made available at ccMixter. You also acknowledge that under all Creative Commons licenses, you are granted a license to use the tracks only; all rights not expressly granted under the terms of the license are reserved to the creator. You represent and warrant to ArtisTech Media that you will use any and all tracks made available at ccMixter in accordance with the applicable license.</p>
<p class="p4"></p>
<p class="p3">For the avoidance of doubt, you must attribute all tracks in the manner required by the author or licensor and in accordance with the terms of the applicable Creative Commons license and you must not remove or alter any copyright, trademark, name or other notice or legend that appears in connection with a track.</p>
<p class="p3"><b>About the ccMixter site generally</b>: ArtisTech Media makes ccMixter available to you on these terms. You may only use ccMixter in accordance with these terms and, in particular but without limitation, you may not use ccMixter for any purpose that is unlawful or prohibited by these terms or any other conditions or notices that are made available at ccMixter. For example, you may not (and may not authorize another party to): (i) frame or otherwise co-brand this site (for example, by displaying a name, logo, trademark or other means of attribution of a third party that is reasonably likely to give the user the impression that that third party has the right to display, publish or distribute this site; or, (ii) use ccMixter in any manner that could disable, overburden, damage or impair the ccMixter or interfere with any other party's use and enjoyment of ccMixter.</p>
<p class="p4"></p>
<p class="p3"><b>About the music you post to ccMixter:</b> You may only post music to ccMixter that you have the right to post and license under a Creative Commons license. For example, this means that you can only post music that you yourself create, music that is in the public domain or any other material that you have the express permission to use and license to the world, for example, under a Creative Commons Sampling Plus license or a Creative Commons Noncommercial Sampling Plus license. For the avoidance of doubt, materials that infringe the rights of any third party (ie. materials used without express permission of the copyright owner) may not be used.</p>
<p class="p4"></p>
<p class="p3">By submitting music to ccMixter, you represent and warrant to ArtisTech Media that you have the necessary rights and authority to upload the track to <a href="http://ccmixter.org/"><span class="s1">http://ccmixter.org</span></a> site and license it to the world under the Creative Commons license that you apply to that music.</p>
<p class="p4"></p>
<p class="p3"><b>What you may do with ccHost:</b> ArtisTech Media makes ccHost, the software that runs the ccMixter site, available under a CC-GNU-GPL license (<a href="http://creativecommons.org/licenses/GPL/2.0"><span class="s1">http://creativecommons.org/licenses/GPL/2.0</span></a>/). You may use ccHost in accordance with the terms of that license. You agree that you are solely responsible for your use of ccHost and you represent and warrant to ArtisTech Media that your use of ccHost will comply with the CC-GNU-GPL.</p>
<p class="p4"></p>
<p class="p3"><b>Your conduct in the discussion forums:</b> ArtisTech Media offers the discussion forums on ccMixter for you and the other users of ccMixter to discuss music, tracks on ccMixter and directly related issues. You may only use the discussion forums to post, send and receive messages that properly conform to these terms of use and are related to the purpose for which the forums are made available. This means, for example but without limitation, that you must not post or otherwise make available any:</p>
<p class="p3"><span class="s2">-<span class="Apple-tab-span">	</span></span>Material that you do not have the right to post, for example, under intellectual property, confidentiality, privacy or other applicable laws;</p>
<p class="p3"><span class="s2">-<span class="Apple-tab-span">	</span></span>Unsolicited or unauthorized materials, including advertising or promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of unsolicited or unwelcome solicitation or advertising.</p>
<p class="p3"><span class="s2">-<span class="Apple-tab-span">	</span></span>Material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment or otherwise interfere with or disrupt the ccMixter site or servers or networks connected to the ccMixter site, or that disobeys any requirements, procedures, policies or regulations of networks connected to the ccMixter site.</p>
<p class="p3"><span class="s2">-<span class="Apple-tab-span">	</span></span>Material that is harmful, offensive, obscene, abusive, invasive of privacy, defamatory, hateful or otherwise discriminatory, false and misleading, incites an illegal act, or is otherwise in breach of your obligations to any person or contrary to any applicable laws and regulations.</p>
<p class="p4"></p>
<p class="p3">ArtisTech Media is not responsible for the content at ccMixter.org and by using the ccMixter site, you represent that you understand that all information and content made available at or submitted to the ccMixter site is the sole responsibility of the person from which such content originated. You also acknowledge that ArtisTech Media does not make any representations or warranties, including without limitation, about the accuracy, integrity or quality of the content and information made available at the instigation of users of the ccMixter site. You understand that by using ccMixter, you may be exposed to content that is offensive, indecent or objectionable. Under no circumstances is ArtisTech Media liable in any way for any content, including, but not limited to: any infringing content, any errors or omissions in content, or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available via the ccMixter site.</p>
<p class="p4"></p>
<p class="p3">You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or reliability of such content. In this regard, you acknowledge that you may not rely on any content not created by us or submitted to us, including without limitation information in any of our public forums, and in all other parts of the ccMixter site.</p>
<p class="p4"></p>
<p class="p3">You further agree that, while ArtisTech Media makes efforts to ensure that the content made available at ccMixter is legal, noninfringing and that the use of it in accordance with the ccMixter Terms and the applicable Creative Commons license will not infringe the rights of any third party, ArtisTech Media cannot guarantee that all content made available at this site does not infringe the rights of any third party. In the event that content is posted to ccMixter and made available for download that is subsequently found to be infringing, ArtisTech Media will undertake reasonable efforts to notify you about this, for example, by posting a notice to the discussion forum or contacting you via email in accordance with the ccMixter Privacy Policy.</p>
<p class="p4"></p>
<p class="p3"><b>Links to third party sites:</b> The ccMixter site may contain links to third party sites that are not operated and controlled by ArtisTech Media. You acknowledge that ArtisTech Media: (a) is not responsible or liable for any third party site, including without limitation, the content, information or products made available at any third party site for third party linked sites; (b) has not reviewed any third party linked sites; (c) has not sponsored or otherwise endorsed third party linked sites; and (d) makes no representations or warranties about any third party linked sites. For the avoidance of doubt, the only sites operated and controlled by ArtisTech Media, in addition to ccMixter, are <a href="http://tunetrack.net/"><span class="s1">http://tunetrack.net</span></a> and <a href="http://artistechmedia.com/"><span class="s1">http://artistechmedia.com</span></a>.</p>
<p class="p4"></p>
<p class="p3"><b>ArtisTech Media's rights to remove content &amp; change the site:</b> ArtisTech is not required to pre-screen content submitted to and made available at the ccMixter site, however ArtisTech Media has the right (but not the obligation) in our sole discretion to refuse or remove any content that is submitted to and made available via the ccMixter site.</p>
<p class="p4"></p>
<p class="p3">In addition, ArtisTech Media may, at any time: (a) modify, suspend or terminate the operation of or access to the ccMixter site or any portion of the ccMixter site for any reason; (b) modify or change the ccMixter site or any portion of the ccMixter site and any applicable terms and policies governing the use of the ccMixter site; (c) interrupt the operation of the ccMixter site or any portion of the ccMixter site, as necessary. ArtisTech Media will use reasonable efforts to notify you in advance about any modification, suspension or termination.</p>
<p class="p4"></p>
<p class="p3"><b>About the personal information you submit to ccMixter:</b> ArtisTech Media agrees to use your personal information in accordance with the <a href="http://ccmixter.org/privacy"><span class="s1">ccMixter Privacy Policy</span></a> and these terms.</p>
<p class="p4"></p>
<p class="p3">All users of the ccMixter site who upload material or post content to the ccMixter site must provide accurate information upon registering at the Registration page to enable us to contact them. It is your responsibility to ensure that ArtisTech Media has up-to-date contact information for you.</p>
<p class="p4"></p>
<p class="p3">You agree that, in the event that ccMixter is served with an infringement notice under section 512(c)(1)(C) of the US Copyright Act, ArtisTech Media will have taken reasonable steps (as required by section 512(g)(2)) if it promptly notifies you using the latest contact details you provided via the ccMixter Registration page.</p>
<p class="p4"></p>
<p class="p3">You further agree that ccMixter is authorized to disclose any information that is necessary to satisfy any applicable law, regulation, legal process, court order, or government request.</p>
<p class="p4"></p>
<p class="p3"><b>DISCLAIMER OF WARRANTY:</b> TO THE FULLEST EXTENT PERMITTED BY THE APPLICABLE LAW, ARTISTECH MEDIA OFFERS ccMIXTER AS-IS AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING ccMIXTER, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTIBILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT. ARTISTECH MEDIA DOES NOT WARRANT THAT THE FUNCTIONS OR CONTENT CONTAINED IN THIS SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ARTISTECH MEDIA DOES NOT WARRANT OR MAKE ANY REPRESENTATION REGARDING USE OR THE RESULT OF USE OF THE CONTENT IN TERMS OF ACCURACY, RELIABILITY, OR OTHERWISE.</p>
<p class="p4"></p>
<p class="p3"><b>LIMITATION OF LIABILITY:</b> EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW AND THEN ONLY TO THAT EXTENT, IN NO EVENT WILL ARTISTECH MEDIA, ITS EMPLOYEES, OFFICERS, DIRECTORS, AFFILIATES OR AGENTS ("THE ARTISTECH MEDIA PARTIES") BE LIABLE TO YOU ON ANY LEGAL THEORY FOR ANY INCIDENTAL, DIRECT, INDIRECT, PUNITIVE, ACTUAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR OTHER DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF REVENUE OR INCOME, LOST PROFITS, PAIN AND SUFFERING, EMOTIONAL DISTRESS OR SIMILAR DAMAGES SUFFERED OR INCURRED BY YOU OR ANY THIRD PARTY THAT ARISE IN CONNECTION WITH THE ccMIXTER SITE OR THE USE OF ANY MATERIAL INCLUDED AT ccMIXTER, EVEN IF THE ARTISTECH MEDIA PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
<p class="p4"></p>
<p class="p3"><b>Termination:</b> Your right to use the ccMixter site terminates automatically upon your breach of any of these terms. ArtisTech Media also reserves the right to, in its sole discretion, terminate your access to all or any part of ccMixter at any time without notice.</p>
<p class="p4"></p>
<p class="p3">You indemnify ArtisTech Media for your breach of these terms: You agree to indemnify and hold harmless the ArtisTech Media Parties (as defined above) from and against any and all loss, expenses, damages and costs, including without limitation reasonable attorneys fees, resulting, whether directly or indirectly, from your violation of these terms. You also agree to indemnify and hold harmless the ArtisTech Media Parties (as defined above) from and against any and all claims brought by third parties arising out of your use of the ccMixter site and the content made available via the ccMixter site.</p>
<p class="p4"></p>
<p class="p3"><b>Trademarks:</b> ccMixter may contain trademarks, service marks, logos and other names that are the property of ArtisTech Media or the Creative Commons or such other party as indicated with respect to that name or icon. In the case of Creative Commons' trademarks, logos and icons, these may only be used in accordance with their trademark policy (<a href="http://creativecommons.org/policies"><span class="s1">http://creativecommons.org/policies</span></a>).</p>
<p class="p4"></p>
<p class="p3"><b>DMCA Compliance:</b> ArtisTech Media complies with the provisions of the Digital Millennium Copyright Act (DMCA). In compliance with the DMCA, a Designated Agent has been established with proper documentation sent to the US Copyright Office. If you have a concern regarding the use of copyrighted material on any ArtisTech Media Web Site, please contact the agent designated to respond to reports alleging copyright infringement. The designated agent for Sponsor to receive notification of claimed infringement under Title II of the DMCA is:</p>
<p class="p4"></p>
<p class="p3">Emily Richards</p>
<p class="p5"><span class="s3"><a href="file:///Users/emily/Documents/%22mailto:">info@artistechmedia.com</a></span></p>
<p class="p3">ArtisTech Media, LLC<br />
10606 Camino Ruiz, Ste 8-244<br />
San Diego, CA 92126<br />
Fax: 810-454-1663<br />
<p class="p4"></p>
<p class="p3"><b>General:</b> (a) These terms are governed by and construed by the laws of the State of California, USA, exclusive of its choice of law rules. (b) You agree that any disputes or proceedings between ArtisTech Media and you concerning these terms and ccMixter shall be brought in a federal or state court of competent jurisdiction sitting in California, US. (c) ArtisTech Media's failure to insist on or enforce strict performance of any of these terms shall not be construed as a waiver of any provision or right. (d) If any of these provisions is held to be invalid or unenforceable by any law or regulation or final determination of a competent court or tribunal, that provision will be deemed severable and will not affect the validity and enforceability of any remaining provisions. (e) You agree that no joint venture, partnership, employment, or agency relationship exists between you and ArtisTech Media as a result of these terms or your use of ccMixter. (f) These terms constitute the entire agreement between you and ArtisTech Media relating to this subject matter and supersedes all prior, contemporaneous and future communications (with the exception of future amendments to these terms as made available by ArtisTech Media from time to time) between you and ArtisTech Media. (g) A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based on or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generating and maintained in printed form. (h) ArtisTech Media may revise these terms at any time by updating this posting and posting a notice in the discussion forum.</p>
</div>
